# @package _global_
defaults:
  - mode: local
  - dataset: cifar10
  - model: cnn
  - trainer: pytorch
  - _self_

logs_dir: /checkpoint/${oc.env:USER}/logs/fair-getting-started-recipe/${now:%Y-%m-%d_%H-%M-%S}

# tells hydra to store logs for sweeps or runs in logs_dir
hydra:
  job:
    # when exceuting a job change to the logs_dir
    chdir: True
  run:
    dir: ${logs_dir}
  sweep:
    dir: ${logs_dir}
